# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:             
     - jekyll-paginate
     - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Egor Tolstoy
tagline:          'iOS Developer'
description:      'iOS Team Lead @ <a href="http://rambler-co.ru/" target="_blank">Rambler&Co</a>.<br> Interested in software design and task automation.<br>Twitter: <a href="http://twitter.com/igrekde" target="_blank">@igrekde</a>'
url:              http://etolstoy.ru
baseurl:          /
excerpt_separator: <!--more-->

author:
  name:           'Egor Tolstoy'
  email:          'igrekde@gmail.com'
  url:            https://twitter.com/etolstoy
  email_md5:      faf4a633b0d1e32a07a071039686c868

paginate:         5

# Custom vars
version:          2.1.0
linkedin:         'https://www.linkedin.com/in/etolstoy'
github:           'https://github.com/etolstoy'
